/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LMJAQUiModule extends AbstractLMJAQUiModule {

	public LMJAQUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
