/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lmjaq.ui.internal.LmjaqActivator;

public class LMJAQUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LmjaqActivator.getInstance().getInjector("org.xtext.lmjaq.LMJAQ");
	}

}
