/*
 * generated by Xtext 2.25.0
 */
grammar InternalLMJAQ;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.lmjaq.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.lmjaq.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.lmjaq.services.LMJAQGrammarAccess;

}

@parser::members {

 	private LMJAQGrammarAccess grammarAccess;

    public InternalLMJAQParser(TokenStream input, LMJAQGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected LMJAQGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getModelAccess().getAbstractElmentsAbstractElementParserRuleCall_0());
			}
			lv_abstractElments_0_0=ruleAbstractElement
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getModelRule());
				}
				add(
					$current,
					"abstractElments",
					lv_abstractElments_0_0,
					"org.xtext.lmjaq.LMJAQ.AbstractElement");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleAbstractElement
entryRuleAbstractElement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractElementRule()); }
	iv_ruleAbstractElement=ruleAbstractElement
	{ $current=$iv_ruleAbstractElement.current; }
	EOF;

// Rule AbstractElement
ruleAbstractElement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractElementAccess().getElementTypePackageDeclarationParserRuleCall_0_0());
				}
				lv_elementType_0_1=rulePackageDeclaration
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractElementRule());
					}
					set(
						$current,
						"elementType",
						lv_elementType_0_1,
						"org.xtext.lmjaq.LMJAQ.PackageDeclaration");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractElementAccess().getElementTypeAbstractClassParserRuleCall_0_1());
				}
				lv_elementType_0_2=ruleAbstractClass
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractElementRule());
					}
					set(
						$current,
						"elementType",
						lv_elementType_0_2,
						"org.xtext.lmjaq.LMJAQ.AbstractClass");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRulePackageDeclaration
entryRulePackageDeclaration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPackageDeclarationRule()); }
	iv_rulePackageDeclaration=rulePackageDeclaration
	{ $current=$iv_rulePackageDeclaration.current; }
	EOF;

// Rule PackageDeclaration
rulePackageDeclaration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='package'
		{
			newLeafNode(otherlv_0, grammarAccess.getPackageDeclarationAccess().getPackageKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPackageDeclarationAccess().getNameQualifiedNameParserRuleCall_1_0());
				}
				lv_name_1_0=ruleQualifiedName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPackageDeclarationRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"org.xtext.lmjaq.LMJAQ.QualifiedName");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleQualifiedName
entryRuleQualifiedName returns [String current=null]:
	{ newCompositeNode(grammarAccess.getQualifiedNameRule()); }
	iv_ruleQualifiedName=ruleQualifiedName
	{ $current=$iv_ruleQualifiedName.current.getText(); }
	EOF;

// Rule QualifiedName
ruleQualifiedName returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_0());
		}
		(
			kw='.'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getQualifiedNameAccess().getFullStopKeyword_1_0());
			}
			this_ID_2=RULE_ID
			{
				$current.merge(this_ID_2);
			}
			{
				newLeafNode(this_ID_2, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_1_1());
			}
		)*
	)
;

// Entry rule entryRuleAbstractClass
entryRuleAbstractClass returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractClassRule()); }
	iv_ruleAbstractClass=ruleAbstractClass
	{ $current=$iv_ruleAbstractClass.current; }
	EOF;

// Rule AbstractClass
ruleAbstractClass returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassAccess().getTypeAbstractClassTypeParserRuleCall_0_0());
				}
				lv_type_0_0=ruleAbstractClassType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassRule());
					}
					set(
						$current,
						"type",
						lv_type_0_0,
						"org.xtext.lmjaq.LMJAQ.AbstractClassType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				(
					lv_name_1_1=RULE_ID
					{
						newLeafNode(lv_name_1_1, grammarAccess.getAbstractClassAccess().getNameIDTerminalRuleCall_1_0_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getAbstractClassRule());
						}
						setWithLastConsumed(
							$current,
							"name",
							lv_name_1_1,
							"org.eclipse.xtext.common.Terminals.ID");
					}
					    |
					lv_name_1_2=RULE_EVENT_CODE
					{
						newLeafNode(lv_name_1_2, grammarAccess.getAbstractClassAccess().getNameEVENT_CODETerminalRuleCall_1_0_1());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getAbstractClassRule());
						}
						setWithLastConsumed(
							$current,
							"name",
							lv_name_1_2,
							"org.xtext.lmjaq.LMJAQ.EVENT_CODE");
					}
				)
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getAbstractClassAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassAccess().getAbstractPropertiesAbstractPropertyParserRuleCall_3_0());
				}
				lv_abstractProperties_3_0=ruleAbstractProperty
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassRule());
					}
					add(
						$current,
						"abstractProperties",
						lv_abstractProperties_3_0,
						"org.xtext.lmjaq.LMJAQ.AbstractProperty");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getAbstractClassAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleAbstractClassType
entryRuleAbstractClassType returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractClassTypeRule()); }
	iv_ruleAbstractClassType=ruleAbstractClassType
	{ $current=$iv_ruleAbstractClassType.current; }
	EOF;

// Rule AbstractClassType
ruleAbstractClassType returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeTelaParserRuleCall_0_0());
				}
				lv_type_0_1=ruleTela
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_1,
						"org.xtext.lmjaq.LMJAQ.Tela");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeObjetoParserRuleCall_0_1());
				}
				lv_type_0_2=ruleObjeto
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_2,
						"org.xtext.lmjaq.LMJAQ.Objeto");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeRecursoParserRuleCall_0_2());
				}
				lv_type_0_3=ruleRecurso
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_3,
						"org.xtext.lmjaq.LMJAQ.Recurso");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeComponenteParserRuleCall_0_3());
				}
				lv_type_0_4=ruleComponente
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_4,
						"org.xtext.lmjaq.LMJAQ.Componente");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeEventoComplexoParserRuleCall_0_4());
				}
				lv_type_0_5=ruleEventoComplexo
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_5,
						"org.xtext.lmjaq.LMJAQ.EventoComplexo");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeConfigGeralParserRuleCall_0_5());
				}
				lv_type_0_6=ruleConfigGeral
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_6,
						"org.xtext.lmjaq.LMJAQ.ConfigGeral");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeEstadoParserRuleCall_0_6());
				}
				lv_type_0_7=ruleEstado
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_7,
						"org.xtext.lmjaq.LMJAQ.Estado");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeItemParserRuleCall_0_7());
				}
				lv_type_0_8=ruleItem
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_8,
						"org.xtext.lmjaq.LMJAQ.Item");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeAlternativaParserRuleCall_0_8());
				}
				lv_type_0_9=ruleAlternativa
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_9,
						"org.xtext.lmjaq.LMJAQ.Alternativa");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getAbstractClassTypeAccess().getTypeQuestaoParserRuleCall_0_9());
				}
				lv_type_0_10=ruleQuestao
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassTypeRule());
					}
					set(
						$current,
						"type",
						lv_type_0_10,
						"org.xtext.lmjaq.LMJAQ.Questao");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleTela
entryRuleTela returns [String current=null]:
	{ newCompositeNode(grammarAccess.getTelaRule()); }
	iv_ruleTela=ruleTela
	{ $current=$iv_ruleTela.current.getText(); }
	EOF;

// Rule Tela
ruleTela returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Tela'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getTelaAccess().getTelaKeyword());
	}
;

// Entry rule entryRuleObjeto
entryRuleObjeto returns [String current=null]:
	{ newCompositeNode(grammarAccess.getObjetoRule()); }
	iv_ruleObjeto=ruleObjeto
	{ $current=$iv_ruleObjeto.current.getText(); }
	EOF;

// Rule Objeto
ruleObjeto returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Objeto'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getObjetoAccess().getObjetoKeyword());
	}
;

// Entry rule entryRuleAbstractProperty
entryRuleAbstractProperty returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractPropertyRule()); }
	iv_ruleAbstractProperty=ruleAbstractProperty
	{ $current=$iv_ruleAbstractProperty.current; }
	EOF;

// Rule AbstractProperty
ruleAbstractProperty returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getAbstractPropertyAccess().getFormatClassReferenceParserRuleCall_0_0_0());
					}
					lv_format_0_1=ruleClassReference
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAbstractPropertyRule());
						}
						set(
							$current,
							"format",
							lv_format_0_1,
							"org.xtext.lmjaq.LMJAQ.ClassReference");
						afterParserOrEnumRuleCall();
					}
					    |
					{
						newCompositeNode(grammarAccess.getAbstractPropertyAccess().getFormatPropertyParserRuleCall_0_0_1());
					}
					lv_format_0_2=ruleProperty
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAbstractPropertyRule());
						}
						set(
							$current,
							"format",
							lv_format_0_2,
							"org.xtext.lmjaq.LMJAQ.Property");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)
		otherlv_1=':'
		{
			newLeafNode(otherlv_1, grammarAccess.getAbstractPropertyAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractPropertyAccess().getValuesValueParserRuleCall_2_0());
				}
				lv_values_2_0=ruleValue
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractPropertyRule());
					}
					add(
						$current,
						"values",
						lv_values_2_0,
						"org.xtext.lmjaq.LMJAQ.Value");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleClassReference
entryRuleClassReference returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getClassReferenceRule()); }
	iv_ruleClassReference=ruleClassReference
	{ $current=$iv_ruleClassReference.current; }
	EOF;

// Rule ClassReference
ruleClassReference returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getClassReferenceAccess().getTypeAbstractClassTypeParserRuleCall_0());
			}
			lv_type_0_0=ruleAbstractClassType
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getClassReferenceRule());
				}
				set(
					$current,
					"type",
					lv_type_0_0,
					"org.xtext.lmjaq.LMJAQ.AbstractClassType");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleProperty
entryRuleProperty returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPropertyRule()); }
	iv_ruleProperty=ruleProperty
	{ $current=$iv_ruleProperty.current; }
	EOF;

// Rule Property
ruleProperty returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypePosicaoParserRuleCall_0_0());
				}
				lv_propertyType_0_1=rulePosicao
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_1,
						"org.xtext.lmjaq.LMJAQ.Posicao");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEstaAtivoParserRuleCall_0_1());
				}
				lv_propertyType_0_2=ruleestaAtivo
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_2,
						"org.xtext.lmjaq.LMJAQ.estaAtivo");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeCaminhoParserRuleCall_0_2());
				}
				lv_propertyType_0_3=ruleCaminho
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_3,
						"org.xtext.lmjaq.LMJAQ.Caminho");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeTamanhoDaFonteParserRuleCall_0_3());
				}
				lv_propertyType_0_4=ruleTamanhoDaFonte
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_4,
						"org.xtext.lmjaq.LMJAQ.TamanhoDaFonte");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeConteudoParserRuleCall_0_4());
				}
				lv_propertyType_0_5=ruleConteudo
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_5,
						"org.xtext.lmjaq.LMJAQ.Conteudo");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeTamanhoParserRuleCall_0_5());
				}
				lv_propertyType_0_6=ruleTamanho
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_6,
						"org.xtext.lmjaq.LMJAQ.Tamanho");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeIUParserRuleCall_0_6());
				}
				lv_propertyType_0_7=ruleIU
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_7,
						"org.xtext.lmjaq.LMJAQ.IU");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEventoSimplesParserRuleCall_0_7());
				}
				lv_propertyType_0_8=ruleEventoSimples
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_8,
						"org.xtext.lmjaq.LMJAQ.EventoSimples");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeComprimentoDaTelaParserRuleCall_0_8());
				}
				lv_propertyType_0_9=ruleComprimentoDaTela
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_9,
						"org.xtext.lmjaq.LMJAQ.ComprimentoDaTela");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeAlturaDaTelaParserRuleCall_0_9());
				}
				lv_propertyType_0_10=ruleAlturaDaTela
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_10,
						"org.xtext.lmjaq.LMJAQ.AlturaDaTela");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEfeitoParserRuleCall_0_10());
				}
				lv_propertyType_0_11=ruleEfeito
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_11,
						"org.xtext.lmjaq.LMJAQ.Efeito");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEstadosAfetadosParserRuleCall_0_11());
				}
				lv_propertyType_0_12=ruleEstadosAfetados
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_12,
						"org.xtext.lmjaq.LMJAQ.EstadosAfetados");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEstadoInicialParserRuleCall_0_12());
				}
				lv_propertyType_0_13=ruleEstadoInicial
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_13,
						"org.xtext.lmjaq.LMJAQ.EstadoInicial");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEstadoFinalParserRuleCall_0_13());
				}
				lv_propertyType_0_14=ruleEstadoFinal
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_14,
						"org.xtext.lmjaq.LMJAQ.EstadoFinal");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeProximoEstadosParserRuleCall_0_14());
				}
				lv_propertyType_0_15=ruleProximoEstados
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_15,
						"org.xtext.lmjaq.LMJAQ.ProximoEstados");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeFormatoQuizParserRuleCall_0_15());
				}
				lv_propertyType_0_16=ruleFormatoQuiz
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_16,
						"org.xtext.lmjaq.LMJAQ.FormatoQuiz");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeEnunciadoParserRuleCall_0_16());
				}
				lv_propertyType_0_17=ruleEnunciado
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_17,
						"org.xtext.lmjaq.LMJAQ.Enunciado");
					afterParserOrEnumRuleCall();
				}
				    |
				{
					newCompositeNode(grammarAccess.getPropertyAccess().getPropertyTypeRespostaParserRuleCall_0_17());
				}
				lv_propertyType_0_18=ruleResposta
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPropertyRule());
					}
					set(
						$current,
						"propertyType",
						lv_propertyType_0_18,
						"org.xtext.lmjaq.LMJAQ.Resposta");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleestaAtivo
entryRuleestaAtivo returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEstaAtivoRule()); }
	iv_ruleestaAtivo=ruleestaAtivo
	{ $current=$iv_ruleestaAtivo.current.getText(); }
	EOF;

// Rule estaAtivo
ruleestaAtivo returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Ativo'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEstaAtivoAccess().getAtivoKeyword());
	}
;

// Entry rule entryRuleIU
entryRuleIU returns [String current=null]:
	{ newCompositeNode(grammarAccess.getIURule()); }
	iv_ruleIU=ruleIU
	{ $current=$iv_ruleIU.current.getText(); }
	EOF;

// Rule IU
ruleIU returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='IU'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getIUAccess().getIUKeyword());
	}
;

// Entry rule entryRulePosicao
entryRulePosicao returns [String current=null]:
	{ newCompositeNode(grammarAccess.getPosicaoRule()); }
	iv_rulePosicao=rulePosicao
	{ $current=$iv_rulePosicao.current.getText(); }
	EOF;

// Rule Posicao
rulePosicao returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Posicao'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getPosicaoAccess().getPosicaoKeyword());
	}
;

// Entry rule entryRuleValue
entryRuleValue returns [String current=null]:
	{ newCompositeNode(grammarAccess.getValueRule()); }
	iv_ruleValue=ruleValue
	{ $current=$iv_ruleValue.current.getText(); }
	EOF;

// Rule Value
ruleValue returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getValueAccess().getIDTerminalRuleCall_0());
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getBooleanParserRuleCall_1());
		}
		this_Boolean_1=ruleBoolean
		{
			$current.merge(this_Boolean_1);
		}
		{
			afterParserOrEnumRuleCall();
		}
		    |
		this_UNITYINTDECIMAL_2=RULE_UNITYINTDECIMAL
		{
			$current.merge(this_UNITYINTDECIMAL_2);
		}
		{
			newLeafNode(this_UNITYINTDECIMAL_2, grammarAccess.getValueAccess().getUNITYINTDECIMALTerminalRuleCall_2());
		}
		    |
		this_INTEGER_3=RULE_INTEGER
		{
			$current.merge(this_INTEGER_3);
		}
		{
			newLeafNode(this_INTEGER_3, grammarAccess.getValueAccess().getINTEGERTerminalRuleCall_3());
		}
		    |
		this_PATH_4=RULE_PATH
		{
			$current.merge(this_PATH_4);
		}
		{
			newLeafNode(this_PATH_4, grammarAccess.getValueAccess().getPATHTerminalRuleCall_4());
		}
		    |
		this_UI_TYPE_5=RULE_UI_TYPE
		{
			$current.merge(this_UI_TYPE_5);
		}
		{
			newLeafNode(this_UI_TYPE_5, grammarAccess.getValueAccess().getUI_TYPETerminalRuleCall_5());
		}
		    |
		this_SIMPLE_EVENT_TYPE_6=RULE_SIMPLE_EVENT_TYPE
		{
			$current.merge(this_SIMPLE_EVENT_TYPE_6);
		}
		{
			newLeafNode(this_SIMPLE_EVENT_TYPE_6, grammarAccess.getValueAccess().getSIMPLE_EVENT_TYPETerminalRuleCall_6());
		}
		    |
		this_EVENT_CODE_7=RULE_EVENT_CODE
		{
			$current.merge(this_EVENT_CODE_7);
		}
		{
			newLeafNode(this_EVENT_CODE_7, grammarAccess.getValueAccess().getEVENT_CODETerminalRuleCall_7());
		}
		    |
		this_EFEITO_ACTION_8=RULE_EFEITO_ACTION
		{
			$current.merge(this_EFEITO_ACTION_8);
		}
		{
			newLeafNode(this_EFEITO_ACTION_8, grammarAccess.getValueAccess().getEFEITO_ACTIONTerminalRuleCall_8());
		}
		    |
		this_TEXT_CONTENT_9=RULE_TEXT_CONTENT
		{
			$current.merge(this_TEXT_CONTENT_9);
		}
		{
			newLeafNode(this_TEXT_CONTENT_9, grammarAccess.getValueAccess().getTEXT_CONTENTTerminalRuleCall_9());
		}
	)
;

// Entry rule entryRuleComponente
entryRuleComponente returns [String current=null]:
	{ newCompositeNode(grammarAccess.getComponenteRule()); }
	iv_ruleComponente=ruleComponente
	{ $current=$iv_ruleComponente.current.getText(); }
	EOF;

// Rule Componente
ruleComponente returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getComponenteAccess().getGatilhoParserRuleCall_0());
		}
		this_Gatilho_0=ruleGatilho
		{
			$current.merge(this_Gatilho_0);
		}
		{
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getComponenteAccess().getComportamentoParserRuleCall_1());
		}
		this_Comportamento_1=ruleComportamento
		{
			$current.merge(this_Comportamento_1);
		}
		{
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleEventoComplexo
entryRuleEventoComplexo returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEventoComplexoRule()); }
	iv_ruleEventoComplexo=ruleEventoComplexo
	{ $current=$iv_ruleEventoComplexo.current.getText(); }
	EOF;

// Rule EventoComplexo
ruleEventoComplexo returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='EventoComplexo'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEventoComplexoAccess().getEventoComplexoKeyword());
	}
;

// Entry rule entryRuleEventoSimples
entryRuleEventoSimples returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEventoSimplesRule()); }
	iv_ruleEventoSimples=ruleEventoSimples
	{ $current=$iv_ruleEventoSimples.current.getText(); }
	EOF;

// Rule EventoSimples
ruleEventoSimples returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='EventoSimples'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEventoSimplesAccess().getEventoSimplesKeyword());
	}
;

// Entry rule entryRuleGatilho
entryRuleGatilho returns [String current=null]:
	{ newCompositeNode(grammarAccess.getGatilhoRule()); }
	iv_ruleGatilho=ruleGatilho
	{ $current=$iv_ruleGatilho.current.getText(); }
	EOF;

// Rule Gatilho
ruleGatilho returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	{
		newCompositeNode(grammarAccess.getGatilhoAccess().getAoClicarParserRuleCall());
	}
	this_AoClicar_0=ruleAoClicar
	{
		$current.merge(this_AoClicar_0);
	}
	{
		afterParserOrEnumRuleCall();
	}
;

// Entry rule entryRuleAoClicar
entryRuleAoClicar returns [String current=null]:
	{ newCompositeNode(grammarAccess.getAoClicarRule()); }
	iv_ruleAoClicar=ruleAoClicar
	{ $current=$iv_ruleAoClicar.current.getText(); }
	EOF;

// Rule AoClicar
ruleAoClicar returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='AoClicar'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getAoClicarAccess().getAoClicarKeyword());
	}
;

// Entry rule entryRuleComportamento
entryRuleComportamento returns [String current=null]:
	{ newCompositeNode(grammarAccess.getComportamentoRule()); }
	iv_ruleComportamento=ruleComportamento
	{ $current=$iv_ruleComportamento.current.getText(); }
	EOF;

// Rule Comportamento
ruleComportamento returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Comportamento'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getComportamentoAccess().getComportamentoKeyword());
	}
;

// Entry rule entryRuleRecurso
entryRuleRecurso returns [String current=null]:
	{ newCompositeNode(grammarAccess.getRecursoRule()); }
	iv_ruleRecurso=ruleRecurso
	{ $current=$iv_ruleRecurso.current.getText(); }
	EOF;

// Rule Recurso
ruleRecurso returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRecursoAccess().getImagemParserRuleCall_0());
		}
		this_Imagem_0=ruleImagem
		{
			$current.merge(this_Imagem_0);
		}
		{
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRecursoAccess().getAnimacaoParserRuleCall_1());
		}
		this_Animacao_1=ruleAnimacao
		{
			$current.merge(this_Animacao_1);
		}
		{
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRecursoAccess().getTextoParserRuleCall_2());
		}
		this_Texto_2=ruleTexto
		{
			$current.merge(this_Texto_2);
		}
		{
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleImagem
entryRuleImagem returns [String current=null]:
	{ newCompositeNode(grammarAccess.getImagemRule()); }
	iv_ruleImagem=ruleImagem
	{ $current=$iv_ruleImagem.current.getText(); }
	EOF;

// Rule Imagem
ruleImagem returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Imagem'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getImagemAccess().getImagemKeyword());
	}
;

// Entry rule entryRuleAnimacao
entryRuleAnimacao returns [String current=null]:
	{ newCompositeNode(grammarAccess.getAnimacaoRule()); }
	iv_ruleAnimacao=ruleAnimacao
	{ $current=$iv_ruleAnimacao.current.getText(); }
	EOF;

// Rule Animacao
ruleAnimacao returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Animacao'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getAnimacaoAccess().getAnimacaoKeyword());
	}
;

// Entry rule entryRuleTexto
entryRuleTexto returns [String current=null]:
	{ newCompositeNode(grammarAccess.getTextoRule()); }
	iv_ruleTexto=ruleTexto
	{ $current=$iv_ruleTexto.current.getText(); }
	EOF;

// Rule Texto
ruleTexto returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Texto'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getTextoAccess().getTextoKeyword());
	}
;

// Entry rule entryRuleConteudo
entryRuleConteudo returns [String current=null]:
	{ newCompositeNode(grammarAccess.getConteudoRule()); }
	iv_ruleConteudo=ruleConteudo
	{ $current=$iv_ruleConteudo.current.getText(); }
	EOF;

// Rule Conteudo
ruleConteudo returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Conteudo'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getConteudoAccess().getConteudoKeyword());
	}
;

// Entry rule entryRuleTamanho
entryRuleTamanho returns [String current=null]:
	{ newCompositeNode(grammarAccess.getTamanhoRule()); }
	iv_ruleTamanho=ruleTamanho
	{ $current=$iv_ruleTamanho.current.getText(); }
	EOF;

// Rule Tamanho
ruleTamanho returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Tamanho'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getTamanhoAccess().getTamanhoKeyword());
	}
;

// Entry rule entryRuleTamanhoDaFonte
entryRuleTamanhoDaFonte returns [String current=null]:
	{ newCompositeNode(grammarAccess.getTamanhoDaFonteRule()); }
	iv_ruleTamanhoDaFonte=ruleTamanhoDaFonte
	{ $current=$iv_ruleTamanhoDaFonte.current.getText(); }
	EOF;

// Rule TamanhoDaFonte
ruleTamanhoDaFonte returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='TamanhoDaFonte'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getTamanhoDaFonteAccess().getTamanhoDaFonteKeyword());
	}
;

// Entry rule entryRuleCaminho
entryRuleCaminho returns [String current=null]:
	{ newCompositeNode(grammarAccess.getCaminhoRule()); }
	iv_ruleCaminho=ruleCaminho
	{ $current=$iv_ruleCaminho.current.getText(); }
	EOF;

// Rule Caminho
ruleCaminho returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Caminho'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getCaminhoAccess().getCaminhoKeyword());
	}
;

// Entry rule entryRuleConfigGeral
entryRuleConfigGeral returns [String current=null]:
	{ newCompositeNode(grammarAccess.getConfigGeralRule()); }
	iv_ruleConfigGeral=ruleConfigGeral
	{ $current=$iv_ruleConfigGeral.current.getText(); }
	EOF;

// Rule ConfigGeral
ruleConfigGeral returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='ConfigGeral'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getConfigGeralAccess().getConfigGeralKeyword());
	}
;

// Entry rule entryRuleComprimentoDaTela
entryRuleComprimentoDaTela returns [String current=null]:
	{ newCompositeNode(grammarAccess.getComprimentoDaTelaRule()); }
	iv_ruleComprimentoDaTela=ruleComprimentoDaTela
	{ $current=$iv_ruleComprimentoDaTela.current.getText(); }
	EOF;

// Rule ComprimentoDaTela
ruleComprimentoDaTela returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='ComprimentoDaTela'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getComprimentoDaTelaAccess().getComprimentoDaTelaKeyword());
	}
;

// Entry rule entryRuleAlturaDaTela
entryRuleAlturaDaTela returns [String current=null]:
	{ newCompositeNode(grammarAccess.getAlturaDaTelaRule()); }
	iv_ruleAlturaDaTela=ruleAlturaDaTela
	{ $current=$iv_ruleAlturaDaTela.current.getText(); }
	EOF;

// Rule AlturaDaTela
ruleAlturaDaTela returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='AlturaDaTela'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getAlturaDaTelaAccess().getAlturaDaTelaKeyword());
	}
;

// Entry rule entryRuleQuestao
entryRuleQuestao returns [String current=null]:
	{ newCompositeNode(grammarAccess.getQuestaoRule()); }
	iv_ruleQuestao=ruleQuestao
	{ $current=$iv_ruleQuestao.current.getText(); }
	EOF;

// Rule Questao
ruleQuestao returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Questao'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getQuestaoAccess().getQuestaoKeyword());
	}
;

// Entry rule entryRuleAlternativa
entryRuleAlternativa returns [String current=null]:
	{ newCompositeNode(grammarAccess.getAlternativaRule()); }
	iv_ruleAlternativa=ruleAlternativa
	{ $current=$iv_ruleAlternativa.current.getText(); }
	EOF;

// Rule Alternativa
ruleAlternativa returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Alternativa'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getAlternativaAccess().getAlternativaKeyword());
	}
;

// Entry rule entryRuleEnunciado
entryRuleEnunciado returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEnunciadoRule()); }
	iv_ruleEnunciado=ruleEnunciado
	{ $current=$iv_ruleEnunciado.current.getText(); }
	EOF;

// Rule Enunciado
ruleEnunciado returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Enunciado'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEnunciadoAccess().getEnunciadoKeyword());
	}
;

// Entry rule entryRuleResposta
entryRuleResposta returns [String current=null]:
	{ newCompositeNode(grammarAccess.getRespostaRule()); }
	iv_ruleResposta=ruleResposta
	{ $current=$iv_ruleResposta.current.getText(); }
	EOF;

// Rule Resposta
ruleResposta returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Resposta'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getRespostaAccess().getRespostaKeyword());
	}
;

// Entry rule entryRuleFormatoQuiz
entryRuleFormatoQuiz returns [String current=null]:
	{ newCompositeNode(grammarAccess.getFormatoQuizRule()); }
	iv_ruleFormatoQuiz=ruleFormatoQuiz
	{ $current=$iv_ruleFormatoQuiz.current.getText(); }
	EOF;

// Rule FormatoQuiz
ruleFormatoQuiz returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='FormatoQuiz'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getFormatoQuizAccess().getFormatoQuizKeyword());
	}
;

// Entry rule entryRuleEstado
entryRuleEstado returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEstadoRule()); }
	iv_ruleEstado=ruleEstado
	{ $current=$iv_ruleEstado.current.getText(); }
	EOF;

// Rule Estado
ruleEstado returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Estado'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEstadoAccess().getEstadoKeyword());
	}
;

// Entry rule entryRuleEstadoFinal
entryRuleEstadoFinal returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEstadoFinalRule()); }
	iv_ruleEstadoFinal=ruleEstadoFinal
	{ $current=$iv_ruleEstadoFinal.current.getText(); }
	EOF;

// Rule EstadoFinal
ruleEstadoFinal returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='EstadoFinal'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEstadoFinalAccess().getEstadoFinalKeyword());
	}
;

// Entry rule entryRuleEstadoInicial
entryRuleEstadoInicial returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEstadoInicialRule()); }
	iv_ruleEstadoInicial=ruleEstadoInicial
	{ $current=$iv_ruleEstadoInicial.current.getText(); }
	EOF;

// Rule EstadoInicial
ruleEstadoInicial returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='EstadoInicial'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEstadoInicialAccess().getEstadoInicialKeyword());
	}
;

// Entry rule entryRuleProximoEstados
entryRuleProximoEstados returns [String current=null]:
	{ newCompositeNode(grammarAccess.getProximoEstadosRule()); }
	iv_ruleProximoEstados=ruleProximoEstados
	{ $current=$iv_ruleProximoEstados.current.getText(); }
	EOF;

// Rule ProximoEstados
ruleProximoEstados returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='ProximoEstados'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getProximoEstadosAccess().getProximoEstadosKeyword());
	}
;

// Entry rule entryRuleItem
entryRuleItem returns [String current=null]:
	{ newCompositeNode(grammarAccess.getItemRule()); }
	iv_ruleItem=ruleItem
	{ $current=$iv_ruleItem.current.getText(); }
	EOF;

// Rule Item
ruleItem returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Item'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getItemAccess().getItemKeyword());
	}
;

// Entry rule entryRuleEfeito
entryRuleEfeito returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEfeitoRule()); }
	iv_ruleEfeito=ruleEfeito
	{ $current=$iv_ruleEfeito.current.getText(); }
	EOF;

// Rule Efeito
ruleEfeito returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='Efeito'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEfeitoAccess().getEfeitoKeyword());
	}
;

// Entry rule entryRuleEstadosAfetados
entryRuleEstadosAfetados returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEstadosAfetadosRule()); }
	iv_ruleEstadosAfetados=ruleEstadosAfetados
	{ $current=$iv_ruleEstadosAfetados.current.getText(); }
	EOF;

// Rule EstadosAfetados
ruleEstadosAfetados returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='EstadosAfetados'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getEstadosAfetadosAccess().getEstadosAfetadosKeyword());
	}
;

// Entry rule entryRuleBoolean
entryRuleBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getBooleanRule()); }
	iv_ruleBoolean=ruleBoolean
	{ $current=$iv_ruleBoolean.current.getText(); }
	EOF;

// Rule Boolean
ruleBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_FALSE_0=RULE_FALSE
		{
			$current.merge(this_FALSE_0);
		}
		{
			newLeafNode(this_FALSE_0, grammarAccess.getBooleanAccess().getFALSETerminalRuleCall_0());
		}
		    |
		this_TRUE_1=RULE_TRUE
		{
			$current.merge(this_TRUE_1);
		}
		{
			newLeafNode(this_TRUE_1, grammarAccess.getBooleanAccess().getTRUETerminalRuleCall_1());
		}
	)
;

RULE_TEXT_CONTENT : RULE_STRING;

RULE_EFEITO_ACTION : ('[Bloqueia]'|'[Adiciona]');

RULE_UI_TYPE : ('[Botao]'|'[Imagem]'|'[Animacao]'|'[Texto]');

RULE_SIMPLE_EVENT_TYPE : '[proximaTela]';

RULE_UNITYINTDECIMAL : ('0'..'9')+ '.' '0'..'9';

RULE_INTEGER : '1'..'9' ('0'..'9')+;

RULE_PATH : RULE_SLASH (RULE_ID RULE_SLASH)*;

fragment RULE_SLASH : ('/'|'\b');

RULE_FALSE : 'false';

RULE_TRUE : 'true';

RULE_EVENT_CODE : 'A'..'Z' 'A'..'Z' 'A'..'Z' ('0'..'9')+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

fragment RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
