/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LMJAQStandaloneSetup extends LMJAQStandaloneSetupGenerated {

	public static void doSetup() {
		new LMJAQStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
