/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractElement#getElementType <em>Element Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractElement()
 * @model
 * @generated
 */
public interface AbstractElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Type</em>' containment reference.
   * @see #setElementType(EObject)
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractElement_ElementType()
   * @model containment="true"
   * @generated
   */
  EObject getElementType();

  /**
   * Sets the value of the '{@link org.xtext.lmjaq.lMJAQ.AbstractElement#getElementType <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Type</em>' containment reference.
   * @see #getElementType()
   * @generated
   */
  void setElementType(EObject value);

} // AbstractElement
