/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getAbstractProperties <em>Abstract Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractClass()
 * @model
 * @generated
 */
public interface AbstractClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(AbstractClassType)
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractClass_Type()
   * @model containment="true"
   * @generated
   */
  AbstractClassType getType();

  /**
   * Sets the value of the '{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(AbstractClassType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Abstract Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.lmjaq.lMJAQ.AbstractProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Properties</em>' containment reference list.
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractClass_AbstractProperties()
   * @model containment="true"
   * @generated
   */
  EList<AbstractProperty> getAbstractProperties();

} // AbstractClass
