/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractProperty#getFormat <em>Format</em>}</li>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.AbstractProperty#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractProperty()
 * @model
 * @generated
 */
public interface AbstractProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Format</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' containment reference.
   * @see #setFormat(EObject)
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractProperty_Format()
   * @model containment="true"
   * @generated
   */
  EObject getFormat();

  /**
   * Sets the value of the '{@link org.xtext.lmjaq.lMJAQ.AbstractProperty#getFormat <em>Format</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' containment reference.
   * @see #getFormat()
   * @generated
   */
  void setFormat(EObject value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getAbstractProperty_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // AbstractProperty
