/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.lmjaq.lMJAQ.LMJAQFactory
 * @model kind="package"
 * @generated
 */
public interface LMJAQPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lMJAQ";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/lmjaq/LMJAQ";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lMJAQ";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LMJAQPackage eINSTANCE = org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.ModelImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Abstract Elments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ABSTRACT_ELMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.AbstractElementImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__ELEMENT_TYPE = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.PackageDeclarationImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractClassImpl <em>Abstract Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.AbstractClassImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractClass()
   * @generated
   */
  int ABSTRACT_CLASS = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__NAME = 1;

  /**
   * The feature id for the '<em><b>Abstract Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__ABSTRACT_PROPERTIES = 2;

  /**
   * The number of structural features of the '<em>Abstract Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractClassTypeImpl <em>Abstract Class Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.AbstractClassTypeImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractClassType()
   * @generated
   */
  int ABSTRACT_CLASS_TYPE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS_TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Abstract Class Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractPropertyImpl <em>Abstract Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.AbstractPropertyImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractProperty()
   * @generated
   */
  int ABSTRACT_PROPERTY = 5;

  /**
   * The feature id for the '<em><b>Format</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROPERTY__FORMAT = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROPERTY__VALUES = 1;

  /**
   * The number of structural features of the '<em>Abstract Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.ClassReferenceImpl <em>Class Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.ClassReferenceImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getClassReference()
   * @generated
   */
  int CLASS_REFERENCE = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_REFERENCE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Class Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_REFERENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lmjaq.lMJAQ.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lmjaq.lMJAQ.impl.PropertyImpl
   * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 7;

  /**
   * The feature id for the '<em><b>Property Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__PROPERTY_TYPE = 0;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.lmjaq.lMJAQ.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lmjaq.lMJAQ.Model#getAbstractElments <em>Abstract Elments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Abstract Elments</em>'.
   * @see org.xtext.lmjaq.lMJAQ.Model#getAbstractElments()
   * @see #getModel()
   * @generated
   */
  EReference getModel_AbstractElments();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lmjaq.lMJAQ.AbstractElement#getElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractElement#getElementType()
   * @see #getAbstractElement()
   * @generated
   */
  EReference getAbstractElement_ElementType();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see org.xtext.lmjaq.lMJAQ.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lmjaq.lMJAQ.PackageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lmjaq.lMJAQ.PackageDeclaration#getName()
   * @see #getPackageDeclaration()
   * @generated
   */
  EAttribute getPackageDeclaration_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.AbstractClass <em>Abstract Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Class</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClass
   * @generated
   */
  EClass getAbstractClass();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClass#getType()
   * @see #getAbstractClass()
   * @generated
   */
  EReference getAbstractClass_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClass#getName()
   * @see #getAbstractClass()
   * @generated
   */
  EAttribute getAbstractClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lmjaq.lMJAQ.AbstractClass#getAbstractProperties <em>Abstract Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Abstract Properties</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClass#getAbstractProperties()
   * @see #getAbstractClass()
   * @generated
   */
  EReference getAbstractClass_AbstractProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.AbstractClassType <em>Abstract Class Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Class Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClassType
   * @generated
   */
  EClass getAbstractClassType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lmjaq.lMJAQ.AbstractClassType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractClassType#getType()
   * @see #getAbstractClassType()
   * @generated
   */
  EAttribute getAbstractClassType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.AbstractProperty <em>Abstract Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Property</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractProperty
   * @generated
   */
  EClass getAbstractProperty();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lmjaq.lMJAQ.AbstractProperty#getFormat <em>Format</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Format</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractProperty#getFormat()
   * @see #getAbstractProperty()
   * @generated
   */
  EReference getAbstractProperty_Format();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.lmjaq.lMJAQ.AbstractProperty#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.lmjaq.lMJAQ.AbstractProperty#getValues()
   * @see #getAbstractProperty()
   * @generated
   */
  EAttribute getAbstractProperty_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.ClassReference <em>Class Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Reference</em>'.
   * @see org.xtext.lmjaq.lMJAQ.ClassReference
   * @generated
   */
  EClass getClassReference();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lmjaq.lMJAQ.ClassReference#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.ClassReference#getType()
   * @see #getClassReference()
   * @generated
   */
  EReference getClassReference_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.lmjaq.lMJAQ.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.lmjaq.lMJAQ.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lmjaq.lMJAQ.Property#getPropertyType <em>Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property Type</em>'.
   * @see org.xtext.lmjaq.lMJAQ.Property#getPropertyType()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_PropertyType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LMJAQFactory getLMJAQFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.ModelImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Abstract Elments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ABSTRACT_ELMENTS = eINSTANCE.getModel_AbstractElments();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.AbstractElementImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Element Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_ELEMENT__ELEMENT_TYPE = eINSTANCE.getAbstractElement_ElementType();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.PackageDeclarationImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECLARATION__NAME = eINSTANCE.getPackageDeclaration_Name();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractClassImpl <em>Abstract Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.AbstractClassImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractClass()
     * @generated
     */
    EClass ABSTRACT_CLASS = eINSTANCE.getAbstractClass();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_CLASS__TYPE = eINSTANCE.getAbstractClass_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_CLASS__NAME = eINSTANCE.getAbstractClass_Name();

    /**
     * The meta object literal for the '<em><b>Abstract Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_CLASS__ABSTRACT_PROPERTIES = eINSTANCE.getAbstractClass_AbstractProperties();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractClassTypeImpl <em>Abstract Class Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.AbstractClassTypeImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractClassType()
     * @generated
     */
    EClass ABSTRACT_CLASS_TYPE = eINSTANCE.getAbstractClassType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_CLASS_TYPE__TYPE = eINSTANCE.getAbstractClassType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.AbstractPropertyImpl <em>Abstract Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.AbstractPropertyImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getAbstractProperty()
     * @generated
     */
    EClass ABSTRACT_PROPERTY = eINSTANCE.getAbstractProperty();

    /**
     * The meta object literal for the '<em><b>Format</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_PROPERTY__FORMAT = eINSTANCE.getAbstractProperty_Format();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_PROPERTY__VALUES = eINSTANCE.getAbstractProperty_Values();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.ClassReferenceImpl <em>Class Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.ClassReferenceImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getClassReference()
     * @generated
     */
    EClass CLASS_REFERENCE = eINSTANCE.getClassReference();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_REFERENCE__TYPE = eINSTANCE.getClassReference_Type();

    /**
     * The meta object literal for the '{@link org.xtext.lmjaq.lMJAQ.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lmjaq.lMJAQ.impl.PropertyImpl
     * @see org.xtext.lmjaq.lMJAQ.impl.LMJAQPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Property Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__PROPERTY_TYPE = eINSTANCE.getProperty_PropertyType();

  }

} //LMJAQPackage
