/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.Model#getAbstractElments <em>Abstract Elments</em>}</li>
 * </ul>
 *
 * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Abstract Elments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.lmjaq.lMJAQ.AbstractElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Elments</em>' containment reference list.
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getModel_AbstractElments()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getAbstractElments();

} // Model
