/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.lMJAQ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lmjaq.lMJAQ.Property#getPropertyType <em>Property Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Property Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Type</em>' attribute.
   * @see #setPropertyType(String)
   * @see org.xtext.lmjaq.lMJAQ.LMJAQPackage#getProperty_PropertyType()
   * @model
   * @generated
   */
  String getPropertyType();

  /**
   * Sets the value of the '{@link org.xtext.lmjaq.lMJAQ.Property#getPropertyType <em>Property Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Type</em>' attribute.
   * @see #getPropertyType()
   * @generated
   */
  void setPropertyType(String value);

} // Property
