/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLMJAQScopeProvider extends DelegatingScopeProvider {
}
