/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lmjaq.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LMJAQAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/lmjaq/parser/antlr/internal/InternalLMJAQ.tokens");
	}
}
